name: Go

on:
  push:
    branches: ["develop", "release"]
  pull_request:
    branches: ["develop", "release"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build cmd/main.go  

      - name: Test
        run: go test -v ./...
